name: CD GitOps

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.6

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            higorrsc/fc-hrsc-gitops:${{ github.sha }}
            higorrsc/fc-hrsc-gitops:latest

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v2
        with:
          kustomize-version: "v5.4.1"

      - name: Update Kubernetes resources
        run: |
          cd k8s
          kustomize edit set image goserver=${{ vars.DOCKERHUB_USERNAME }}/fc-hrsc-gitops:${{ github.sha }}

      - name: Commit kustomization changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add k8s/kustomization.yaml
          # Commit only if there are changes
          if ! git diff --staged --quiet; then
            git commit -m "Update image tag to ${{ github.sha }} [ci skip]"
          fi

      - name: Push kustomization changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}
